CREATE TABLE IF NOT EXISTS public.users
(
    password character varying(128) COLLATE pg_catalog."default",
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    email_verified boolean NOT NULL,
    is_active boolean NOT NULL,
    oauth_provider character varying(100) COLLATE pg_catalog."default",
    oauth_provider_id character varying(255) COLLATE pg_catalog."default",
    two_factor_enabled boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    lockout_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_login_at timestamp with time zone,
    role_id integer,
    status_change_reason character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);




CREATE TABLE IF NOT EXISTS public.email_verification_table
(
    id bigint NOT NULL DEFAULT nextval('email_verification_table_id_seq'::regclass),
    user_id uuid NOT NULL,
    verification_type_id integer NOT NULL,
    token text COLLATE pg_catalog."default",
    otp character varying(6) COLLATE pg_catalog."default",
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT email_verification_table_pkey PRIMARY KEY (id),
    CONSTRAINT email_verification_table_token_key UNIQUE (token),
    CONSTRAINT ev_type_fk FOREIGN KEY (verification_type_id)
        REFERENCES public.verification_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT ev_user_fk FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS public.user_refresh_tokens
(
    token_id    integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id     uuid NOT NULL,
    refresh_token text NOT NULL,
    expires_at  timestamp with time zone NOT NULL,
    is_revoked  boolean NOT NULL DEFAULT false,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT user_refresh_tokens_pkey PRIMARY KEY (token_id),
    CONSTRAINT user_refresh_tokens_refresh_token_key UNIQUE (refresh_token),

    CONSTRAINT user_refresh_tokens_user_id_fk FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);


