CREATE TABLE IF NOT EXISTS public.doctors
(
    doctor_id uuid NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    experience_years numeric(6,2) NOT NULL,
    phone_number character varying(15) COLLATE pg_catalog."default" NOT NULL,
    consultation_fee numeric(10,2),
    registration_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    profile_image character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    gender_id integer,
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verification_notes text COLLATE pg_catalog."default",
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT doctors_pkey PRIMARY KEY (doctor_id),
    CONSTRAINT doctors_gender_id_9b833a22_fk_genders_gender_id FOREIGN KEY (gender_id)
        REFERENCES public.genders (gender_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctors_user_id_480f6e79_fk_users_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctors_verified_by_id_659a9c03_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS public.appointment_slots
(
    slot_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slot_date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    is_booked boolean NOT NULL DEFAULT false,
    is_blocked boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL,
    schedule_id integer NOT NULL,
    CONSTRAINT appointment_slots_pkey PRIMARY KEY (slot_id),
    CONSTRAINT appointment_slots_schedule_id_slot_date_st_c77aed6c_uniq UNIQUE (schedule_id, slot_date, start_time),
    CONSTRAINT appointment_slots_schedule_id_768ac7d2_fk_doctor_sc FOREIGN KEY (schedule_id)
        REFERENCES public.doctor_schedules (schedule_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT appointment_slots_time_check CHECK (start_time < end_time)
)


CREATE TABLE IF NOT EXISTS public.doctor_appointments
(
    appointment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    appointment_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    cancellation_reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cancelled_by_id uuid,
    doctor_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    slot_id integer,
    CONSTRAINT doctor_appointments_pkey PRIMARY KEY (appointment_id),
    CONSTRAINT doctor_appointments_cancelled_by_id_80395a1b_fk_users_user_id FOREIGN KEY (cancelled_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_appointments_doctor_id_4f36d1d1_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_appointments_patient_id_f8f9a694_fk_users_user_id FOREIGN KEY (patient_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_appointments_slot_id_bd041bf6_fk_appointme FOREIGN KEY (slot_id)
        REFERENCES public.appointment_slots (slot_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS public.doctor_qualifications
(
    doctor_qualification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    institution character varying(255) COLLATE pg_catalog."default",
    year_of_completion integer,
    created_at timestamp with time zone NOT NULL,
    doctor_id uuid NOT NULL,
    qualification_id integer NOT NULL,
    CONSTRAINT doctor_qualifications_pkey PRIMARY KEY (doctor_qualification_id),
    CONSTRAINT doctor_qualifications_doctor_id_qualification_id_562aa436_uniq UNIQUE (doctor_id, qualification_id),
    CONSTRAINT doctor_qualification_qualification_id_10a92a5c_fk_qualifica FOREIGN KEY (qualification_id)
        REFERENCES public.qualifications (qualification_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_qualifications_doctor_id_317a2d59_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_qualifications_year_of_completion_check CHECK (year_of_completion >= 0)
);

CREATE TABLE IF NOT EXISTS public.doctor_schedules
(
    schedule_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    consultation_duration_min integer NOT NULL,
    appointment_contact character varying(15) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    doctor_id uuid NOT NULL,
    CONSTRAINT doctor_schedules_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT doctor_schedules_doctor_id_key UNIQUE (doctor_id),
    CONSTRAINT doctor_schedules_doctor_id_44f71506_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_schedules_consultation_duration_min_check CHECK (consultation_duration_min >= 0)
);

CREATE TABLE IF NOT EXISTS public.doctor_specializations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_primary boolean NOT NULL,
    years_in_specialty integer,
    created_at timestamp with time zone NOT NULL,
    doctor_id uuid NOT NULL,
    specialization_id integer NOT NULL,
    CONSTRAINT doctor_specializations_pkey PRIMARY KEY (id),
    CONSTRAINT doctor_specializations_doctor_id_specialization_c54b8458_uniq UNIQUE (doctor_id, specialization_id),
    CONSTRAINT doctor_specializatio_specialization_id_fe05463f_fk_specializ FOREIGN KEY (specialization_id)
        REFERENCES public.specializations (specialization_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_specializations_doctor_id_6874ba84_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_specializations_years_in_specialty_check CHECK (years_in_specialty >= 0)
);

CREATE TABLE IF NOT EXISTS public.doctor_working_days
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    arrival time without time zone,
    leaving time without time zone,
    created_at timestamp with time zone NOT NULL,
    schedule_id integer NOT NULL,
    lunch_end time without time zone,
    lunch_start time without time zone,
    CONSTRAINT doctor_working_days_pkey PRIMARY KEY (id),
    CONSTRAINT doctor_working_days_schedule_id_day_of_week_3a07f362_uniq UNIQUE (schedule_id, day_of_week),
    CONSTRAINT doctor_working_days_schedule_id_67dbb916_fk_doctor_sc FOREIGN KEY (schedule_id)
        REFERENCES public.doctor_schedules (schedule_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_working_days_arrival_leaving_check CHECK (arrival IS NULL OR leaving IS NULL OR arrival < leaving),
    CONSTRAINT doctor_working_days_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);




