CREATE TABLE IF NOT EXISTS public.labs
(
    lab_id uuid NOT NULL,
    lab_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    license_number character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    lab_logo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    verification_notes text COLLATE pg_catalog."default",
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT labs_pkey PRIMARY KEY (lab_id),
    CONSTRAINT labs_license_number_key UNIQUE (license_number),
    CONSTRAINT labs_user_id_354de3c5_fk_users_user_id FOREIGN KEY (lab_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT labs_verified_by_id_089b0662_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);




CREATE TABLE IF NOT EXISTS public.lab_operating_hours
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    is_closed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_operating_hours_pkey PRIMARY KEY (id),
    CONSTRAINT lab_operating_hours_lab_id_day_of_week_bc2fe93e_uniq UNIQUE (lab_id, day_of_week),
    CONSTRAINT lab_operating_hours_lab_id_599b71fb_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_operating_hours_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);

CREATE TABLE IF NOT EXISTS public.lab_services
(
    service_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    service_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10,2),
    turnaround_hours integer,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_services_pkey PRIMARY KEY (service_id),
    CONSTRAINT lab_services_lab_id_service_name_ec2eeece_uniq UNIQUE (lab_id, service_name),
    CONSTRAINT lab_services_lab_id_747daac2_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_services_turnaround_hours_check CHECK (turnaround_hours >= 0)
);
