CREATE TABLE IF NOT EXISTS public.blood_groups
(
    blood_group_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    blood_group_value character varying(5) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT blood_groups_pkey PRIMARY KEY (blood_group_id),
    CONSTRAINT blood_groups_blood_group_value_key UNIQUE (blood_group_value)
)


CREATE TABLE IF NOT EXISTS public.genders
(
    gender_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    gender_value character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT genders_pkey PRIMARY KEY (gender_id),
    CONSTRAINT genders_gender_value_key UNIQUE (gender_value)
)


CREATE TABLE IF NOT EXISTS public.qualifications
(
    qualification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    qualification_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    qualification_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT qualifications_pkey PRIMARY KEY (qualification_id),
    CONSTRAINT qualifications_qualification_code_key UNIQUE (qualification_code),
    CONSTRAINT qualifications_qualification_name_key UNIQUE (qualification_name)
);


CREATE TABLE IF NOT EXISTS public.specializations
(
    specialization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    specialization_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT specializations_pkey PRIMARY KEY (specialization_id),
    CONSTRAINT specializations_specialization_name_key UNIQUE (specialization_name)
);