CREATE TABLE IF NOT EXISTS public.user_roles
(
    role_id serial primary key,
    role character varying(30) COLLATE pg_catalog."default" NOT NULL,
    role_description text COLLATE pg_catalog."default",

    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),

    created_by uuid REFERENCES users(user_id),
    updated_by uuid REFERENCES users(user_id),
	
    CONSTRAINT user_roles_name_key UNIQUE (role)
);


drop table permissions;
drop table role_permissions;

create table if not EXISTS permissions (
    permission_id int generated by DEFAULT as identity primary key,
    module varchar(50) not null,
    action varchar(50) not null,
    description varchar(255),

    created_at timestamp DEFAULT now(),
    updated_at timestamp,

    UNIQUE(module, action)
);


-- Your original DDL has a missing comma before UNIQUE — apply this fix:
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id         INT         NOT NULL REFERENCES user_roles(role_id) ON DELETE CASCADE,
    permission_id   INT         NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
    grant_by        UUID        REFERENCES users(user_id),
    grant_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
);

INSERT INTO permissions (module, action, description) VALUES
  ('patient', 'view', 'View patient records'),
  ('patient', 'toggle_status', 'Activate or deactivate patients'),
  ('doctor', 'view', 'View doctor profiles'),
  ('doctor', 'toggle_status', 'Activate or deactivate doctors'),
  ('doctor', 'verify', 'Mark a doctor as verified'),
  ('lab', 'view', 'View lab entries'),
  ('lab', 'toggle_status', 'Activate or deactivate labs'),
  ('lab', 'verify', 'Mark a lab as verified'),
  ('appointment', 'book', 'Book a new appointment'),
  ('appointment', 'cancel', 'Cancel an existing appointment'),
  ('appointment', 'view_own', 'View own appointments only'),
  ('appointment', 'view_all', 'View all appointments'),
  ('settings', 'view', 'View system settings'),
  ('settings', 'edit', 'Modify system settings');


INSERT INTO public.user_roles (role, role_description) VALUES
  ('ADMIN',         'Full system administrator'),
  ('STAFF',         'Administrative staff member'),
  ('DOCTOR',        'Medical professional'),
  ('PATIENT',       'Healthcare receiver'),
  ('LAB_TECHNICIAN','Medical lab specialist'),
  ('SUPERADMIN',    'Full System Access')
ON CONFLICT (role) DO NOTHING;





-- ================================================================
-- DEFAULT PERMISSIONS ASSIGNMENT
-- Safe to re-run (idempotent via ON CONFLICT DO NOTHING)
-- ================================================================

DO $$
BEGIN

    WITH assignments(role_name, module, action) AS (VALUES

        -- ── SUPERADMIN → everything ──────────────────────────────
        ('SUPERADMIN', 'patient',     'view'),
        ('SUPERADMIN', 'patient',     'toggle_status'),
        ('SUPERADMIN', 'doctor',      'view'),
        ('SUPERADMIN', 'doctor',      'toggle_status'),
        ('SUPERADMIN', 'doctor',      'verify'),
        ('SUPERADMIN', 'lab',         'view'),
        ('SUPERADMIN', 'lab',         'toggle_status'),
        ('SUPERADMIN', 'lab',         'verify'),
        ('SUPERADMIN', 'appointment', 'book'),
        ('SUPERADMIN', 'appointment', 'cancel'),
        ('SUPERADMIN', 'appointment', 'view_own'),
        ('SUPERADMIN', 'appointment', 'view_all'),
        ('SUPERADMIN', 'settings',    'view'),
        ('SUPERADMIN', 'settings',    'edit'),

        -- ── ADMIN → all except settings:edit ─────────────────────
        ('ADMIN', 'patient',     'view'),
        ('ADMIN', 'patient',     'toggle_status'),
        ('ADMIN', 'doctor',      'view'),
        ('ADMIN', 'doctor',      'toggle_status'),
        ('ADMIN', 'doctor',      'verify'),
        ('ADMIN', 'lab',         'view'),
        ('ADMIN', 'lab',         'toggle_status'),
        ('ADMIN', 'lab',         'verify'),
        ('ADMIN', 'appointment', 'book'),
        ('ADMIN', 'appointment', 'cancel'),
        ('ADMIN', 'appointment', 'view_own'),
        ('ADMIN', 'appointment', 'view_all'),
        ('ADMIN', 'settings',    'view'),

        -- ── STAFF → manage patients, doctors, labs + appointments ─
        ('STAFF', 'patient',     'view'),
        ('STAFF', 'patient',     'toggle_status'),
        ('STAFF', 'doctor',      'view'),
        ('STAFF', 'lab',         'view'),
        ('STAFF', 'appointment', 'book'),
        ('STAFF', 'appointment', 'cancel'),
        ('STAFF', 'appointment', 'view_all'),

        -- ── DOCTOR → view patients + own appointments ─────────────
        ('DOCTOR', 'patient',     'view'),
        ('DOCTOR', 'appointment', 'view_own'),
        ('DOCTOR', 'appointment', 'cancel'),

        -- ── PATIENT → own appointments only ──────────────────────
        ('PATIENT', 'appointment', 'book'),
        ('PATIENT', 'appointment', 'cancel'),
        ('PATIENT', 'appointment', 'view_own'),

        -- ── LAB_TECHNICIAN → labs + view patients ─────────────────
        ('LAB_TECHNICIAN', 'patient', 'view'),
        ('LAB_TECHNICIAN', 'lab',     'view')

    )
    INSERT INTO role_permissions (role_id, permission_id)
    SELECT
        r.role_id,
        p.permission_id
    FROM assignments a
    JOIN user_roles  r ON r.role   = a.role_name
    JOIN permissions p ON p.module = a.module
                      AND p.action = a.action
    ON CONFLICT (role_id, permission_id) DO NOTHING;

    RAISE NOTICE 'Default permissions assigned successfully.';

END $$;